### ISSUE TITLE
Output File Still Has Duplicate Frames

### ISSUE THREAD

**Issue by stimpy2k** [Mr-Z-2697/ddfi-rife#8]
Hello.

This appears to be exactly what I'm looking for. I have some media that is 29.97fps, but has duplicate frames in it. It is my goal to eliminate the duplicate frames, and interpolate up to 60fps. ddfi seems to be the right tool for this.

I've been working with it for the last several days, and no matter what I try it seems to leave lots of duplicate frames. I've tried all sorts of -ddt settings, but no matter what I try the output file stills has duplicate frames.

Here are some examples of -ddt settings I've tried...
0.999,10240,2 (default)
0.999,10240,5
0.980,10240,5
0.900,10240,5
0.800,10240,5
0.800,20000,10

Nothing seems to make much of a difference.

Here is a sample source video...
https://gofile.io/d/6NyFV6

And here is an example output from the above sample file (using **-ddt 0.800,10240,5**)...
https://gofile.io/d/c9R1RU

You will see, even in the resulting 60fps output, there are still plenty of duplicate frames there. It's _quite_ possible I'm just doing something wrong. Your help is greatly appreciated. I am using release 2-v1.3.2.

Thanks!

**Comment by Mr-Z-2697** [comment]
Your source video have a lot of artifacts that makes the duplicated frames have pixel differences exceed the second threshold very often even after you increased it to 20000, I suggest setting the threshold to even higher, or even higher than 65536 to effectively disable it.
You can preview parse.vpy to find out some details.

**Comment by Mr-Z-2697** [comment]
Though this script is designed for "anime" content that have many many duplicated frames evenly distributed across the whole time, it may not worth the effort (8x interpolation) with occasional duplicated frames

**Comment by stimpy2k** [comment]
I understand there are only occasional duplicate frames, but that's precisely what I'm trying to address. Your tool seems to be the closest thing I've found for this.

I'll try setting the second ddt value to 65536 and see if that helps. Just so I can make sure I understand clearly, what specifically does each field mean/do? I read the basic information included in the script, but might you be able to explain it in a little more detail?

Thanks again.

**Comment by Mr-Z-2697** [comment]
First threshold is SSIM, higher than threshold means it's considered as duplicate, second threshold is pixel difference (currently only luma plane), higher than threshold means it's considered a different frame, third threshold is how many frames it can consecutively delete.

The second and third threshold are in fact meant to limit the frame deletion.
